"""Project manifest constants."""

MANIFEST_NAME = "1c.project.yaml"
RUNTIME_DIR_NAME = ".runtime"

# Diagnostic codes for project.clean (ADR-021 / #76)
CODE_MANIFEST_MISSING = "1CP001"
CODE_CONFIRM_REQUIRED = "1CP010"
CODE_CLIENT_RUNNING = "1CP011"
CODE_CLEAN_FAILED = "1CP012"
CODE_SOURCE_CLEARED = "1CP013"
CODE_RUNTIME_CLEARED = "1CP014"
CODE_ALREADY_CLEAN = "1CP015"
